#!/bin/bash
export PATH=$PATH:/jet/bin/

#Install Code Deploy Agent - ami-94bfa9f0
sudo yum update -y
sudo yum install -y ruby wget git 
cd /home/ec2-user
wget https://aws-codedeploy-eu-west-2.s3.amazonaws.com/latest/install
sudo chmod +x ./install
sudo ./install auto
