#!/bin/bash

export PATH=$PATH:/jet/bin/
export HOME=/root
export USERPROFILE=/root

cd /jet/app/current

npm install --verbose --unsafe-perm

echo "Deployment Group is : " ${DEPLOYMENT_GROUP_NAME}

aws s3 cp s3://pexeso.io/${DEPLOYMENT_GROUP_NAME}/env .env
aws s3 cp s3://pexeso.io/${DEPLOYMENT_GROUP_NAME}/document_root.settings /jet/etc/www/webservers/nginx/conf.d/

kill $(cat /jet/run/nginx/nginx.pid)
